# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Mine
#' 
#' Calculate the MIC.
#' 
#' @param x a numeric vector
#' @param y another numeric vector
#' @param alpha exponent on (0,1)
#' @param c number of clumps
#'
#' @examples
#' data("iris")
#' mine(iris$Sepal.Length, iris$Sepal.Width)
#'
#' @export
mine <- function(x, y, alpha = .6, c = 15) {
    .Call('minepyRcpp_mine', PACKAGE = 'minepyRcpp', x, y, alpha, c)
}

