# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mine <- function(x, y, alpha = .06, c = 15) {
    .Call('minepyRcpp_mine', PACKAGE = 'minepyRcpp', x, y, alpha, c)
}

